#!/usr/bin/env python3
"""
Generate ANSI half-block art for all character mascots and write to
scripts/mascots-ansi.ts. Run from repo root:

    python3 scripts/generate-mascot-art.py

Requires: Pillow  (pip install pillow)
"""

import json
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Run: pip install pillow")
    sys.exit(1)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASCOTS_DIR = os.path.join(REPO_ROOT, "public", "mascots")
OUTPUT_FILE = os.path.join(REPO_ROOT, "scripts", "mascots-ansi.ts")

WIDTH = 46
HEIGHT = 22

CHAR_MAP: dict[str, str] = {
    "The Intern": "char-the-intern.png",
    "The Degen": "char-the-degen.png",
    "The SBF": "char-the-ghost.png",
    "The Sama": "char-the-operator.png",
    "The Quant": "char-the-quant.png",
    "The Musk": "char-the-chaos-agent.png",
    "The Dario": "char-the-visionary.png",
    "The Karpathy": "char-the-night-shift-engineer.png",
    "Slough Boy": "char-the-researcher.png",
}

ESC = "\x1b"
RESET = f"{ESC}[0m"


def rgb_to_256(r: int, g: int, b: int) -> int:
    ri = round(r / 255 * 5)
    gi = round(g / 255 * 5)
    bi = round(b / 255 * 5)
    return 16 + 36 * ri + 6 * gi + bi


def img_to_ansi(path: str) -> str:
    img = Image.open(path).convert("RGBA")
    img = img.resize((WIDTH, HEIGHT * 2), Image.LANCZOS)

    lines = []
    for row in range(HEIGHT):
        parts: list[str] = []
        cur_fg = cur_bg = -1
        for col in range(WIDTH):
            tr, tg, tb, ta = img.getpixel((col, row * 2))
            br, bg_, bb, ba = img.getpixel((col, row * 2 + 1))
            tc = rgb_to_256(tr, tg, tb) if ta >= 30 else None
            bc = rgb_to_256(br, bg_, bb) if ba >= 30 else None

            if tc is None and bc is None:
                if cur_fg != -1 or cur_bg != -1:
                    parts.append(RESET)
                    cur_fg = cur_bg = -1
                parts.append(" ")
                continue

            if tc is not None and bc is not None:
                new_fg, new_bg, char = bc, tc, "▄"
            elif tc is not None:
                new_fg, new_bg, char = tc, None, "▀"
            else:
                new_fg, new_bg, char = bc, None, "█"

            seq = ""
            if new_bg != cur_bg:
                seq += f"{ESC}[49m" if new_bg is None else f"{ESC}[48;5;{new_bg}m"
                cur_bg = new_bg
            if new_fg != cur_fg:
                seq += f"{ESC}[38;5;{new_fg}m"
                cur_fg = new_fg
            parts.append(seq + char)

        parts.append(RESET)
        cur_fg = cur_bg = -1
        lines.append("".join(parts))

    return "\n".join(lines)


def main() -> None:
    results: dict[str, str] = {}
    total_bytes = 0
    for name, filename in CHAR_MAP.items():
        path = os.path.join(MASCOTS_DIR, filename)
        if not os.path.exists(path):
            print(f"  WARNING: missing {path}")
            continue
        art = img_to_ansi(path)
        results[name] = art
        size = len(art.encode("utf-8"))
        total_bytes += size
        print(f"  {name}: {size:,} bytes")

    print(f"\nTotal: {total_bytes:,} bytes ({total_bytes / 1024:.1f} KB)")

    ts_lines = [
        "// AUTO-GENERATED by scripts/generate-mascot-art.py — do not edit manually",
        "// Pre-rendered ANSI half-block art for all character mascots",
        "// To regenerate: python3 scripts/generate-mascot-art.py",
        "",
        "export const MASCOT_ART: Record<string, string> = {",
    ]
    for name, art in results.items():
        escaped = art.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        ts_lines.append(f"  {json.dumps(name)}: `{escaped}`,")
        ts_lines.append("")
    ts_lines.append("};")
    ts_lines.append("")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(ts_lines))

    print(f"Written: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
